### ISSUE TITLE
Standard configuration seems to throw an error

### ISSUE THREAD

**Issue by tasshin** [JonyEpsilon/incanter-gorilla#2]
I've tried a couple of times now to set up Incanter Gorilla.

Adding lein-gorilla and incanter-Gorilla to the plugins vector of a brand-new project, and then using the initial code from the example worksheet (http://viewer.gorilla-repl.org/view.html?source=github&user=JonyEpsilon&repo=gorilla-test&path=ws/incanter.clj) produces this error:

FileNotFoundException Could not locate incanter_gorilla/render__init.class or incanter_gorilla/render.clj on classpath: clojure.lang.RT.load (RT.java:443)

**Comment by JonyEpsilon** [comment]
`incanter-gorilla` must be specified as a project dependency, not a plugin. Could that be the problem? I've updated the readme to make it a bit clearer.

**Comment by tasshin** [comment]
That definitely was the problem. Thanks Jony! It looks great :)
